/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dungeons.gui;

import Class.Dungeon;
import Dungeons.gui.Game;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CharacterSelection extends javax.swing.JFrame {

    /**
     * Creates new form CustomizeCharacter
     */
    private String knight = null;
    
    public CharacterSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barbarian = new javax.swing.JButton();
        magician = new javax.swing.JButton();
        swordMan = new javax.swing.JButton();
        tank = new javax.swing.JButton();
        assasin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        archer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jknight = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        barbarian.setBackground(new java.awt.Color(0, 0, 0));
        barbarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BarbarianButton.png"))); // NOI18N
        barbarian.setBorder(null);
        barbarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barbarianActionPerformed(evt);
            }
        });

        magician.setBackground(new java.awt.Color(0, 0, 0));
        magician.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/MagicianButton.png"))); // NOI18N
        magician.setBorder(null);
        magician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magicianActionPerformed(evt);
            }
        });

        swordMan.setBackground(new java.awt.Color(0, 0, 0));
        swordMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SwordmanButton.png"))); // NOI18N
        swordMan.setBorder(null);
        swordMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swordManActionPerformed(evt);
            }
        });

        tank.setBackground(new java.awt.Color(0, 0, 0));
        tank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/TankButton.png"))); // NOI18N
        tank.setBorder(null);
        tank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankActionPerformed(evt);
            }
        });

        assasin.setBackground(new java.awt.Color(0, 0, 0));
        assasin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AssasinButton.png"))); // NOI18N
        assasin.setBorder(null);
        assasin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assasinActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Back.png"))); // NOI18N
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        archer.setBackground(new java.awt.Color(0, 0, 0));
        archer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ArcherButton.png"))); // NOI18N
        archer.setBorder(null);
        archer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archerActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CharacterSelection.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Start.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jknight, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(barbarian, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(archer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(swordMan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(magician, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(assasin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tank, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(back))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barbarian)
                            .addComponent(archer))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tank)
                            .addComponent(assasin))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(swordMan)
                            .addComponent(magician))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jknight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addComponent(back)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Menu menu = new Menu();
        menu.setType(getKnight());
        menu.setSize(587, 492);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void archerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archerActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Archer.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Archer");
        setKnight(jknight.getText());
    }//GEN-LAST:event_archerActionPerformed

    private void barbarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barbarianActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Barbarian.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Barbarian");
        setKnight(jknight.getText());
    }//GEN-LAST:event_barbarianActionPerformed

    private void assasinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assasinActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Assasin.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Assasin");
        setKnight(jknight.getText());
    }//GEN-LAST:event_assasinActionPerformed

    private void tankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Tank.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Tank");
        setKnight(jknight.getText());
    }//GEN-LAST:event_tankActionPerformed

    private void swordManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swordManActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("SwordMan.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("SwordMan");
        setKnight(jknight.getText());
    }//GEN-LAST:event_swordManActionPerformed

    private void magicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magicianActionPerformed
        ImageIcon nuevaImagen = new ImageIcon("Magician.png");
        jLabel1.setIcon(nuevaImagen);
        jknight.setText("Magician");
        setKnight(jknight.getText());
        
    }//GEN-LAST:event_magicianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        Dungeon map = new Dungeon(0, 0, 1050, 800, getKnight(),"MapaPruebas.txt" );
        Game gameMap = new Game(map);
        map.setDrawable(gameMap);
        gameMap.setSize(1050, 800);
        gameMap.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archer;
    private javax.swing.JButton assasin;
    private javax.swing.JButton back;
    private javax.swing.JButton barbarian;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jknight;
    private javax.swing.JButton magician;
    private javax.swing.JButton swordMan;
    private javax.swing.JButton tank;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the knight
     */
    public String getKnight() {
        return knight;
    }

    /**
     * @param knight the knight to set
     */
    public void setKnight(String knight) {
        this.knight = knight;
    }
}
